#
# Copyright 2018-2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
dist: trusty
sudo: false
python : "3.6"
language: python
node_js : "10.14"
addons:
  apt:
    packages:
      - python3-pip
before_install:
  # Install YARN [not use NPM]
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt update
  # Setup artifactory registry credentials
  - echo "registry=https://na.artifactory.swg-devops.com/artifactory/api/npm/wcp-wdp-npm-virtual/" >> ~/.npmrc
  - curl -H "X-JFrog-Art-Api:${ARTIFACTORY_KEY}" -X GET https://na.artifactory.swg-devops.com/artifactory/api/npm/auth >> ~/.npmrc
  # Display node/npm version
  - node --version
  - npm --version

install:
  - sudo apt install yarn
  - pip install kfp enterprise_scheduler
  - pip install kfp-notebook --upgrade -i https://$ARTIFACTORY_USER:$ARTIFACTORY_PASS@na.artifactory.swg-devops.com/artifactory/api/pypi/dbg-aiworkspace-team-pypi-local/simple
  - export PATH=$(pwd)/node_modules/.bin:$PATH
  - make bdist
  - pip install ./dist/ai_workspace*.whl
  - jupyter serverextension enable --py ai_workspace --sys-prefix
  # Build the extensions under packages/*
  - pushd packages/notebook-scheduler && jlpm install && popd
  - pushd packages/python-runner && jlpm install && popd
  - pushd packages/pipeline-editor && jlpm install && popd
  # Install the package(s)
  - pushd packages/notebook-scheduler && jupyter labextension link --debug . && popd
  - pushd packages/pipeline-editor && jupyter labextension link --debug . && popd
  - pushd packages/python-runner && jupyter labextension link --debug . && popd
script:
  # Build the python wheel for the extension
  - jupyter labextension list && jupyter serverextension list
  - make test
#deploy:
#after_deploy:
#notifications:
#  slack:
#    rooms:
#      - [slack channel : api token]

after_script:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - cat /home/travis/build/ai-workspace/ai-workspace/*.log
  - cat /home/travis/build/ai-workspace/ai-workspace/packages/enterprise_scheduler_extension/*.log
  - cat /home/travis/build/ai-workspace/ai-workspace/packages/pipeline-editor/*.log
  - cat /home/travis/build/ai-workspace/ai-workspace/packages/python-runner/*.log


group: bluezone
